### ISSUE TITLE
SRT reporter: add flag to download only one transcript per gene (the longest in the result)

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/ApiCommonWebsite#117]
Client:  in https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/185

(also we want to propagate the selection in the step result view filter, to the download form, not sure this will require backend work)

**Comment by wbazant** [comment]
The reporters work off a transcript record - mostly, and sometimes that is transformed to a gene record, but for this feature we start with results of a transcript search. A user could do the transcript search and ask for only the longest transcript, but we don't know that. So, as the reporters work with each transcript record, they will need to check " is it the longest in the result " and if not then report nothing.

**Comment by ryanrdoherty** [comment]
This issue was able to be resolved in client code (using the representative transcript view filter).  No need for a reporter-specific config value.
