### ISSUE TITLE
gene page :  "message": "Invalid dimensions for plot, width = 0, height = 200"

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/ApiCommonWebsite#90]
in a gene page, from trello:

reproduced this! open "Isolate Alignments in this Gene Region", then shrink your window horizontally. At some point, you will get the message. I think a fix would be to set a min-width on a container div of the filter ui."

https://toxodb.org/toxo/app/record/gene/TGME49_247730#total_hts_snps

check:
https://github.com/VEuPathDB/ApiCommonWebsite/blob/master/Site/webapp/wdkCustomization/css/client.scss

**Comment by dmfalke** [comment]
This is still happening: expand the Isolate Alignments section, collapse it, then expand another section. I’m thinking a min-width is also needed.
